"""stdd -- spectral-truncated, drive-directed (noncommutative) graph operators for
inductive classification of quantum phases across a control-parameter sweep.

CPU reference implementation. Every public number this package reports is
generated by running the code (see scripts/ and the Makefile); nothing is
hard-coded. The benchmark is a seeded synthetic phase sweep; real-data hooks
(``ingest``) are honest stubs, never fabricated measurements.
"""
from __future__ import annotations

__version__ = "0.2.0"

from . import (  # noqa: F401
    audit,
    config,
    conformal,
    graph,
    ingest,
    metrics,
    operators,
    persistence,
    plotting,
    policy,
    runner,
    seed,
    splits,
    synthetic,
)
