"""topocell -- Topological Graph RL for Single-Cell State Transition and
Perturbation Forecasting.

CPU reference implementation. Every public number this package reports is
generated by running the code (see scripts/ and the Makefile); nothing is
hard-coded. The benchmark is a seeded synthetic branching lineage; real-data
hooks (``ingest``) are honest stubs, never fabricated measurements.
"""
from __future__ import annotations

__version__ = "0.1.0"

from . import (  # noqa: F401
    audit,
    config,
    graph,
    ingest,
    metrics,
    plotting,
    policy,
    reproduce,
    runner,
    seed,
    splits,
    synthetic,
)
